INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 105);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, true, 104);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 104);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 123);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 123);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 123);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 128);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 128);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 128);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 127);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 127);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 127);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 126);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 126);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 126);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 122);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 122);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 122);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 131);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 131);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 131);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 138);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 138);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 138);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 138);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 121);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 121);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 121);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, true, 110);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 111);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Liquore', true, true, 111);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 95);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 95);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 97);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 97);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 96);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 96);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 73);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 73);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 73);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 73);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aroma', true, true, 81);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 76);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 76);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 76);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 76);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 82);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 82);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 82);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 82);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 78);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 78);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 78);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 78);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 77);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 83);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 83);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 83);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 80);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 80);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 80);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, true, 80);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 75);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 75);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 75);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 79);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 79);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 79);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 79);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 98);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 99);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 103);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 65);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 65);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Contenitore', true, false, 65);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Correzione', true, true, 72);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 70);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 70);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Contenitore', true, false, 70);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 71);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 71);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 66);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 66);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Contenitore', true, false, 66);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 69);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 69);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Contenitore', true, false, 69);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 67);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 67);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Contenitore', true, false, 67);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 133);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Forchette', true, false, 133);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 137);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 137);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 134);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 88);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 88);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 88);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 90);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 90);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 90);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 89);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 89);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 89);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 91);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 91);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, true, 91);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aroma', true, true, 94);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 93);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 93);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, true, 93);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 92);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 92);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, true, 92);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 84);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 84);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 86);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 86);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 85);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 85);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 132);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 132);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 132);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 87);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 87);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 119);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Panna', true, false, 119);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 118);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Panna', true, false, 118);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 120);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Panna', true, false, 120);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 116);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Panna', true, false, 116);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 117);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Panna', true, false, 117);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 136);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 136);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Ingredienti', true, true, 136);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 109);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, true, 108);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 108);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, true, 106);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 106);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, true, 107);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 107);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 101);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 135);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 135);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Cottura', true, false, 135);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Ingredienti', true, false, 135);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 135);



INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (1, 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (1, 'con limone', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (2, 'temp. ambiente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (2, 'fredda', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (3, 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (3, 'con limone', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (4, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (5, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (6, 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (7, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (8, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (9, 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (10, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (11, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (12, 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (13, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (14, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (15, 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (16, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (17, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (18, 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (19, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (20, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (21, 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (22, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (23, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (24, 'abbondante', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (25, 'vegetariana', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (26, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (27, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (28, 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (29, 'liscio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (29, 'dolce', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (30, 'con latte', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (30, 'pistacchio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (30, 'nocciola', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (30, 'caramello', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (30, 'cioccolato', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (31, 'baileys', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (31, 'disaronno', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (32, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (32, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (33, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (33, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (34, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (34, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (35, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (35, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (36, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (36, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (37, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (37, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (38, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (38, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (39, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (39, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (40, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (40, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (40, 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (41, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (41, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (42, 'cioccolato', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (42, 'pistacchio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (42, 'caramello', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (42, 'nutella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (42, 'nocciola', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (43, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (43, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (44, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (44, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (45, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (45, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (45, 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (46, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (46, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (47, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (47, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (48, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (48, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (49, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (49, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (49, 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (50, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (50, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (51, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (51, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (52, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (52, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (53, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (53, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (53, 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (54, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (54, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (55, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (55, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (55, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (55, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (56, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (56, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (57, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (57, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (57, 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (58, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (58, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (59, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (59, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (60, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (60, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (60, 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (61, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (61, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (62, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (62, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (62, 'granella nocciola', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (62, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (62, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (62, 'granella nocciola', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (62, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (62, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (63, 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (63, 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (64, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (65, 'in vetro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (66, 'grappa', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (66, 'sambuca', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (66, 'baileys', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (66, 'disaronno', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (67, 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (67, 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (68, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (69, 'in vetro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (70, 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (70, 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (71, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (72, 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (72, 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (73, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (74, 'in vetro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (75, 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (76, 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (76, 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (77, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (78, 'in vetro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (79, 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (80, 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (80, 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (81, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (82, 'in vetro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (83, 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (84, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (85, 'due forchette', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (86, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (87, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (87, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (88, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (88, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (89, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (89, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (89, 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (90, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (90, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (91, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (91, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (92, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (92, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (92, 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (93, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (93, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (94, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (94, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (95, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (95, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (95, 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (96, 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (96, 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (97, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (97, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (98, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (98, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (98, 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (99, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (99, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (100, 'cioccolato', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (100, 'pistacchio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (100, 'caramello', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (100, 'nutella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (100, 'nocciola', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (101, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (101, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (102, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (102, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (102, 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (103, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (103, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (104, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (104, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (105, 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (105, 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (105, 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (106, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (106, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (107, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (107, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (108, 'con cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (109, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (109, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (110, 'con cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (111, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (111, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (112, 'con cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (113, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (114, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (115, 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (116, 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (116, 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (117, 'con cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (118, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (118, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (119, 'tanta panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (119, 'poca panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (120, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (120, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (121, 'tanta panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (121, 'poca panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (122, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (122, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (123, 'tanta panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (123, 'poca panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (124, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (124, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (125, 'tanta panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (125, 'poca panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (126, 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (126, 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (127, 'tanta panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (127, 'poca panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (128, 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (129, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (130, 'no formaggio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (130, 'no prosciutto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (131, 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (132, 'ambiente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (132, 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (133, 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (134, 'ambiente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (134, 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (135, 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (136, 'ambiente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (136, 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (137, 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (137, 'con limone', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (137, 'latte', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (138, 'diviso in 2', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (139, 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (140, 'ben cotto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (140, 'poco cotto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (141, 'solo prosciutto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (141, 'solo formaggio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES (142, 'abbondante', 0);