PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

ALTER TABLE note RENAME TO note_old;

CREATE TABLE "note" (
    "id" INTEGER NOT NULL,
    "id_gruppo" INTEGER,
    "nome" VARCHAR NOT NULL,
    "price_delta_euro" NUMERIC(8, 2),
    PRIMARY KEY("id"),
    FOREIGN KEY("id_gruppo") REFERENCES "note_gruppi"("id")
);

INSERT INTO "note" ("id", "id_gruppo", "nome", "price_delta_euro")
SELECT "id", "id_gruppo", "nome", "price_delta_euro"
FROM "note_old";

DROP TABLE "note_old";

COMMIT;
PRAGMA foreign_keys = ON;



INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 105);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, true, 104);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 104);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 123);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 123);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 123);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 128);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 128);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 128);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 127);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 127);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 127);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 126);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 126);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 126);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 122);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 122);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 122);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 131);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 131);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 131);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 138);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 138);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 138);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 138);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 121);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 121);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 121);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, true, 110);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 111);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Liquore', true, true, 111);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 95);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 95);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 97);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 97);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 96);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 96);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 73);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 73);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 73);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 73);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aroma', true, true, 81);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 76);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 76);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 76);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 76);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 82);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 82);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 82);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 82);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 78);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 78);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 78);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 78);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 77);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 83);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 83);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 83);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 80);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 80);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 80);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, true, 80);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 75);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 75);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 75);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 79);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 79);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 79);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 79);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 98);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 99);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 103);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 65);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 65);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Contenitore', true, false, 65);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Correzione', true, true, 72);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 70);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 70);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Contenitore', true, false, 70);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 71);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 71);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 66);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 66);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Contenitore', true, false, 66);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 69);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 69);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Contenitore', true, false, 69);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 67);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 67);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Contenitore', true, false, 67);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 133);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Forchette', true, false, 133);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 137);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 137);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 134);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 88);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 88);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 88);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 90);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 90);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 90);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 89);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 89);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, true, 89);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 91);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 91);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, true, 91);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aroma', true, true, 94);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 93);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 93);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, true, 93);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 92);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Schiuma', true, true, 92);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, true, 92);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 84);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 84);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 86);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 86);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 85);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 85);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 132);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 132);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 132);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, false, 87);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Polveri e granelle', true, false, 87);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 119);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Panna', true, false, 119);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 118);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Panna', true, false, 118);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 120);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Panna', true, false, 120);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 116);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Panna', true, false, 116);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Variante', true, false, 117);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Panna', true, false, 117);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 136);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 136);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Ingredienti', true, true, 136);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 109);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, true, 108);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 108);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, true, 106);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 106);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Temperatura', true, true, 107);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 107);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Aggiunta', true, false, 101);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Divisa', true, false, 135);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Asporto', true, false, 135);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Cottura', true, false, 135);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Ingredienti', true, false, 135);
INSERT INTO note_gruppi (nome, esclusivo, obbligatorio_default, id_prodotto) VALUES ('Quantità', true, false, 135);




INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'con limone', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'temp. ambiente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'fredda', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'con limone', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'abbondante', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'vegetariana', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'liscio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'dolce', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'con latte', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'pistacchio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'nocciola', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'caramello', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'cioccolato', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Liquore'), 'baileys', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Liquore'), 'disaronno', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aroma'), 'cioccolato', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aroma'), 'pistacchio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aroma'), 'caramello', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aroma'), 'nutella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aroma'), 'nocciola', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'no schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'granella nocciola', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'granella nocciola', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Contenitore'), 'in vetro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Correzione'), 'grappa', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Correzione'), 'sambuca', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Correzione'), 'baileys', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Correzione'), 'disaronno', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Contenitore'), 'in vetro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Contenitore'), 'in vetro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Contenitore'), 'in vetro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'lungo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'ristretto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Contenitore'), 'in vetro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Forchette'), 'due forchette', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cacao', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aroma'), 'cioccolato', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aroma'), 'pistacchio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aroma'), 'caramello', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aroma'), 'nutella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aroma'), 'nocciola', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'poca schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'tanta schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Schiuma'), 'senza schiuma', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'con cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'con cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'con cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'velo sopra', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'tiepido', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'bollente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Polveri e granelle'), 'con cannella', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Panna'), 'tanta panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Panna'), 'poca panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Panna'), 'tanta panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Panna'), 'poca panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Panna'), 'tanta panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Panna'), 'poca panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Panna'), 'tanta panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Panna'), 'poca panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'chiaro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Variante'), 'scuro', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Panna'), 'tanta panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Panna'), 'poca panna', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'divisa in due', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Ingredienti'), 'no formaggio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Ingredienti'), 'no prosciutto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'ambiente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'ambiente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'ambiente', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Temperatura'), 'freddo', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'con ghiaccio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'con limone', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Aggiunta'), 'latte', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Divisa'), 'diviso in 2', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Asporto'), 'asporto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Cottura'), 'ben cotto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Cottura'), 'poco cotto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Ingredienti'), 'solo prosciutto', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Ingredienti'), 'solo formaggio', 0);
INSERT INTO note (id_gruppo, nome, price_delta_euro) VALUES ((SELECT id FROM note_gruppi WHERE nome = 'Quantità'), 'abbondante', 0);
